# Generated by Django 4.2 on 2026-01-20 11:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
